import { useEffect, useState } from 'react';
import { books as fallbackBooks, awards as fallbackAwards, galleryImages as fallbackGallery } from '../data/content';

export interface MediaItem {
  key: string;
  /** Filename-derived title, used only when a locale entry is missing. */
  title: string;
  /** Full-size image, already resolved against BASE_URL. */
  src: string;
  /** Smaller variant for grids. Falls back to `src` when absent. */
  thumb: string;
  width?: number;
  height?: number;
  aspectRatio?: number;
  /** Inline base64 placeholder shown while loading. */
  blur?: string;
}

interface Manifest {
  generatedAt: string;
  categories: Record<string, MediaItem[]>;
}

type Category = 'gallery' | 'books' | 'awards' | 'family';

const MANIFEST_URL = `${import.meta.env.BASE_URL}data/media.json`;

/** Manifest paths are repo-relative; make them browser-absolute. */
function resolve(item: MediaItem): MediaItem {
  const base = import.meta.env.BASE_URL;
  return {
    ...item,
    src: item.src.startsWith('http') ? item.src : `${base}${item.src}`,
    thumb: item.thumb
      ? item.thumb.startsWith('http')
        ? item.thumb
        : `${base}${item.thumb}`
      : item.src,
  };
}

/** Shape the hardcoded lists like manifest entries, so components stay uniform. */
function fromFallback(category: Category): MediaItem[] {
  const asItem = (key: string, src: string): MediaItem => ({
    key,
    title: key,
    src,
    thumb: src,
  });

  switch (category) {
    case 'books':
      return fallbackBooks.map((b) => asItem(b.key, b.imageSrc));
    case 'awards':
      return fallbackAwards.map((a) => asItem(a.key, a.imageSrc));
    case 'gallery':
      return fallbackGallery.map((g, i) => asItem(`gallery-${i + 1}`, g.imageSrc));
    default:
      return [];
  }
}

let cached: Manifest | null = null;
let inFlight: Promise<Manifest | null> | null = null;

async function loadManifest(): Promise<Manifest | null> {
  if (cached) return cached;
  if (inFlight) return inFlight;

  inFlight = (async () => {
    try {
      const res = await fetch(MANIFEST_URL);
      if (!res.ok) return null;
      const data = (await res.json()) as Manifest;
      if (!data?.categories) return null;
      cached = data;
      return data;
    } catch {
      return null;
    } finally {
      inFlight = null;
    }
  })();

  return inFlight;
}

/**
 * Returns the images for a category.
 *
 * Prefers `public/data/media.json` — generated by `scripts/process-images.mjs`,
 * so adding a file to `public/images/<category>/` is all that is needed.
 * Falls back to the hardcoded lists in `src/data/content.ts` when the manifest
 * has not been generated yet, so the site always renders something.
 */
export function useMediaManifest(category: Category) {
  const [items, setItems] = useState<MediaItem[]>(() => fromFallback(category));
  const [loading, setLoading] = useState(true);
  const [fromManifest, setFromManifest] = useState(false);

  useEffect(() => {
    let cancelled = false;

    loadManifest().then((manifest) => {
      if (cancelled) return;

      const list = manifest?.categories?.[category];
      if (list && list.length > 0) {
        setItems(list.map(resolve));
        setFromManifest(true);
      }
      setLoading(false);
    });

    return () => {
      cancelled = true;
    };
  }, [category]);

  return { items, loading, fromManifest };
}
